create database sales_db;
use sales_db;
show tables;
select * from accounts;
select * from data_dictionary;
select * from products;
select * from sales_pipeline;
select * from sales_teams;

-- Retrieve all accounts located in the 'United States'.
select * from accounts where office_location = "United States";

-- Find all products belonging to the 'GTX' series.
select * from products where series = "GTX";

-- List all unique deal stages from the sales_pipeline table.
select distinct deal_stage from sales_pipeline;

-- Count the total number of sales agents in the sales_teams table.
select count(distinct sales_agent) from sales_teams;

-- Find all accounts established after the year 2000.
select * from accounts where year_established>2000;

-- Retrieve all sales pipeline opportunities where the deal_stage is 'Won'.
select * from sales_pipeline where deal_stage = "Won";

-- Calculate the average number of employees across all accounts.
select avg(employees) from accounts;

-- Get all products with a sales_price greater than 3,000.
select * from products where sales_price>3000;

-- Count the total number of accounts registered under each sector.
select sector,count(account) as count_account from accounts group by sector
order by count_account;

-- Retrieve the list of sales agents managed by 'Dustin Brinkmann'.
select * from sales_teams where manager = "Dustin Brinkmann";

-- Calculate the total closed deal value (close_value) generated by each sales agent for won deals.
select sales_agent,sum(close_value) from sales_pipeline where deal_stage = "Won" group by sales_agent order by 2 desc;

-- Retrieve each sales opportunity along with the agent's manager and regional office.
select * from sales_pipeline sp inner join sales_teams st on sp.sales_agent = st.sales_agent;

-- Find the total revenue and total employees per country (office_location) from the accounts table.
select office_location, sum(revenue), sum(employees) from accounts group by office_location;

-- List all accounts that have subsidiary relationships along with their parent company (subsidiary_of).
select account,sector,parent_company from (select *,  nullif(subsidiary_of,"") AS parent_company from accounts)t 
where parent_company is not null;

-- Calculate total sales revenue (close_value) generated by each regional office.
select st.regional_office,sum(sp.close_value) from sales_pipeline sp inner join sales_teams st on sp.sales_agent = st.sales_agent
group by 1 order by 2 desc;

-- Find the top 5 sales agents who have closed the highest number of 'Won' deals.
select sales_agent,  count(opportunity_id) from sales_pipeline where deal_stage = "Won" group by sales_agent order by 2 desc limit 5;

-- Calculate the average closing value for each product sold in sales_pipeline.
select product,avg(close_value) from sales_pipeline group by product order by 2 desc;

-- Find accounts that have more than 2,000 employees but an annual revenue of less than 1,000 million USD.
select * from accounts where employees>2000 and revenue<1000;

-- Identify products in the products table that have never been included in any sales pipeline deal.
select p.*,sp.* from products p left join sales_pipeline sp on p.product = sp.product where sp.opportunity_id is null;
select p.*,sp.* from products p inner join sales_pipeline sp on p.product = sp.product;

/*Find the total deal value won per sales manager.*/
select st.manager,sum(sp.close_value) from sales_pipeline sp inner join sales_teams st on sp.sales_agent = st.sales_agent where deal_stage = "Won" group by st.manager;

-- Rank sales agents within each regional office based on revenue using DENSE_RANK().
select *,dense_rank() over(partition by regional_office order by count_total_deals desc) from (
select st.regional_office,sp.sales_agent,sum(sp.close_value) over(partition by sp.sales_agent) as count_total_deals
from sales_pipeline sp inner join sales_teams st on sp.sales_agent = st.sales_agent where sp.deal_stage = "Won")t;

-- Calculate the sales velocity (in days) between engage_date and close_date for each won deal, and find the average 
-- sales cycle duration per product.
select product,avg(datediff(close_date,engage_date)) as sales_cycle_per_product
from sales_pipeline group by product order by 2 desc;
select *,round(datediff(close_date,engage_date)) as sales_velocity from sales_pipeline; 

-- Identify accounts where the actual won deal value (close_value) was less than the product's
-- suggested retail price (sales_price).
select sp.product,sp.account
from products p inner join sales_pipeline sp on p.product = sp.product
where p.sales_price>sp.close_value and sp.deal_stage = "Won";

-- Categorize accounts into revenue tiers: 'Enterprise' (> 5,000M), 'Mid-Market' (1,000M–5,000M), and 'SMB' (< 1,000M), 
-- and count accounts per tier.
select *, count(*) over(partition by tier) as count_tier from (
select *, 
case
	when revenue <1000 then "SMB"
    when revenue between 1000 and 5000 then "Mid-Market"
    when revenue >5000 then "Enterprise"
    else "NO IDEA"
end as tier
from accounts)t;

-- Calculate the monthly running total of closed revenue for all won deals ordered by close_date.
select concat(monthname(close_date),year(close_date)), sum(close_value) over(partition by concat(monthname(close_date),year(close_date))
 order by monthname(close_date) rows between unbounded preceding and current row) from sales_pipeline 
 where deal_stage = "Won" order by concat(monthname(close_date),year(close_date));
 
-- Find sales agents whose total won revenue exceeds the average won revenue of agents in their same regional office.
with cte as (
select sp.sales_agent,sp.close_value as revenue,st.regional_office,avg(sp.close_value) over(partition by st.regional_office) as
avg_revenue from sales_pipeline sp inner join sales_teams st on sp.sales_agent = st.sales_agent where sp.deal_stage = "Won")
select * from cte where revenue>avg_revenue ;


-- Identify parent accounts (subsidiary_of) whose total aggregate revenue (including subsidiaries) exceeds 5,000 million USD.
select nullif(subsidiary_of,"")as parent_company,sum(revenue)  from accounts where nullif(subsidiary_of,"") is not null
group by nullif(subsidiary_of,"") having sum(revenue)>5000;


-- Find the top-performing product (by total won revenue) within each regional office.
with cte as (
select *,row_number() over(partition by regional_office order by revenue desc) as rn from (
select sp.product, st.regional_office,sum(sp.close_value) over(partition by st.regional_office,sp.product) as revenue
from sales_pipeline sp inner join sales_teams st on sp.sales_agent = st.sales_agent where sp.deal_stage = "Won")t
)
select * from cte where rn = 1 order by revenue desc;

-- Calculate the conversion rate (Won deals / Total deals * 100) for each sales agent.
select *,round(won_deals*100/total_deals) as conversion_rate from (
select sales_agent,deal_stage,case when deal_stage = "Won" then count(*) over(partition by sales_agent) end as "won_deals",
count(*) over(partition by sales_agent) as total_deals from sales_pipeline)t;

-- Generate a comprehensive manager performance summary displaying manager name, regional office,
-- total team agents, total deals managed, and total won revenue.
select st.manager,st.regional_office,count(sp.sales_agent) as total_team_agent, count(sp.opportunity_id),
sum(sp.close_value) from sales_pipeline sp right join sales_teams st on sp.sales_agent = st.sales_agent
group by st.manager,st.regional_office;
